fieldLayouts:
  06e76407-b135-4cee-ad0d-b31b5c31daa3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecd0291a-c7d5-40eb-baf2-ba805d509e37
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd5a4994-0a39-4020-b7e6-3e1f953feafb # Bio
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 591c623f-c665-4eb0-874c-a11539e7cbbd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4cf5c855-d1af-4592-8af3-9b7ba27d0d64
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b5df3c97-0afb-45b6-9d47-4c266ab769cc # Ticket Types
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
