fieldLayouts:
  85fe2984-9378-4d7c-8d53-c7348ae8d5c9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 70adbfa4-c1d2-4486-b5a6-0f256498b4ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f38eea64-9a8c-4240-955b-3a311f1f1c4c # Seats Available
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1cee8f4-23a7-4e9f-a9e9-74ce28aee3f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a98eefe-41c5-49b3-9608-6b0f9ae77538
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5ff17206-0cb2-4f7f-9523-f6b2119841e4 # Venues
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
