defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  71a06e16-09c8-4a1f-afc1-9e75603074b2: # Demystifying the Craft API
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
